### ISSUE TITLE
Index.hbs missing

### ISSUE THREAD

**Issue by Tarnholm** [teesloane/banquo#4]
Ghost is throwing me errors saying Index.hbs is missing when I try to upload it.

**Comment by teesloane** [comment]
Can you either A) post the steps to recreate the error, or B) post the error that is shown? Both helps too!

I haven't worked on this for a while, but I'm getting a feeling that I ditched the index.hbs file in favor of a home page that you need to set manually... but if it's erroring when you upload that's probably something I need to fix.

Thanks for bringing it up!

T

**Comment by Tarnholm** [comment]
![screenshot 2016-10-04 01 22 14](https://cloud.githubusercontent.com/assets/6020922/19084407/ba8c0e5e-8a66-11e6-853b-6dfde795f486.png)

This is the error I get while uploading the theme to Ghost.

**Comment by teesloane** [comment]
Gotcha. Gonna look into this in a little while. Might be a bit as things are busy right now, but I'll let you know if / when I get this fixed.

**Comment by teesloane** [comment]
@Tarnholm 

It appears that the theme is being installed fine, when installed manually. -- I will not be making any changes to include an index.hbs any time soon (unfortunately). I will make note of this in the readme.
