### ISSUE TITLE
Pagination on 'Blog' page

### ISSUE THREAD

**Issue by junderhill** [teesloane/banquo#5]
I only seem to see the first 15 posts marked with 'note' on the notes page and there is no pagination. 

Am I correct in thinking this hasn't been implemented or am I doing something wrong?

**Comment by junderhill** [comment]
As a temporary fix I have updated the page-notes.hbs to use the following:

`{{#get "posts" filter="tags:note" limit="all"}}`

**Comment by teesloane** [comment]
You are probably correct. Feel like making a pull request? I haven't actually been using the theme so it's altogether likely that I missed this. 

On another note, another user had issues installing this - I'm guessing you didn't? Were the docs clear enough?

**Comment by junderhill** [comment]
Yeah, easy enough to install. No problems at all.

I'll try and get chance to look into the pagination soon, it's definitely something I'd like to implement on my site. If you leave this issue open and I'll try and find some time to sort it.

**Comment by teesloane** [comment]
Fantastic, thanks @junderhill . Glad to hear installation went ok. I'm guessing this has to do with Ghosts' new "upload theme" working -- and that perhaps you just manually moved the theme over in your ghost dir?

edit: will leave this open, if you feel like setting up some kind of pagination, or even just Pr'ing the simple change you made in the interim.

**Comment by junderhill** [comment]
@teesloane Yeah I just cloned the repo on my server, built it with NPM etc. and then copied it to the 'themes' directory.

**Comment by teesloane** [comment]
Great - good to know.
