### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by ghost** [teesloane/banquo#7]
![errors](https://cloud.githubusercontent.com/assets/8988468/19825068/46b48f52-9d75-11e6-80ab-6d063551cda6.PNG)
How can I fix this?  I runned all the command u told my and I activate the template and also did make the proper tags and pages.

**Comment by teesloane** [comment]
Hmm. I'm not sure, I don't have the codebase on my current machine, but from the looks of it, if those files don't exist you can hand-create them manually.

 So you did a `npm install` / `bower install` and compiled the assets with grunt?

**Comment by pointcache** [comment]
i have no idea what i should do but when i upload the zip folder to ghost its broken, and wont install, so yeah, other themes install normally if you cant just make a zip that installs normally i duno.

**Comment by pointcache** [comment]
yeah i tried everything i could through the putty console and all is broken
just make it work with zip archive, why is it so hard

**Comment by teesloane** [comment]
“If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.” 

-Marcus Aurelius

Ps. this project is no longer maintained. ⚓️ 

PPs. — @pointcache -- checked out your website. Nice art!

**Comment by almereyda** [comment]
Unfortunately banquo is not perfectly compatible with modern npm or yarn. I needed to

```
npm i -g grunt
npm i -g bower
yarn install --prod=false # running in a Ghost production container
grunt staging --force #due to an error in jshint:afterconcat
sed -i 's|image|img_url|g' home.hbs
cp home.hbs index.hbs
```

to build the theme sufficiently for Ghost 2.0. Please note that the staging CSS paths are hardcoded, and as such `grunt release` cannot be used. And also note #8.
